platform :ios, '8.0'
target 'DaBangVR' do
pod 'FMDB'
pod 'YYKit'
pod 'Masonry'
pod 'MJRefresh'
pod 'mob_smssdk'
pod 'SDWebImage', '~> 3.7.6'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'IQKeyboardManager' #iOS8 and later
pod 'WechatOpenSDK'
pod 'QQCorner'
pod 'PLMediaStreamingKit'
pod 'PLPlayerKit'
pod 'AZCategory'
pod 'JGProgressHUD'
pod 'MMMaterialDesignSpinner'
pod 'Qiniu'
pod 'SocketRocket'
pod 'JXCategoryView'
end
